ssh x0 "kill -9 $(ps aux | grep "./bin/yb-tserver" | awk '{print $2}')"
ssh x1 "kill -9 $(ps aux | grep "./bin/yb-tserver" | awk '{print $2}')"
ssh x2 "kill -9 $(ps aux | grep "./bin/yb-tserver" | awk '{print $2}')"
ssh x3 "kill -9 $(ps aux | grep "./bin/yb-tserver" | awk '{print $2}')"
ssh x4 "kill -9 $(ps aux | grep "./bin/yb-tserver" | awk '{print $2}')"
